// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHFMA_3F3EO_AAwexwwPaXH73baMqFWpI',
    appId: '1:416064020527:web:44c740a109e1c136ec66da',
    messagingSenderId: '416064020527',
    projectId: 'glowup-95ad5',
    authDomain: 'glowup-95ad5.firebaseapp.com',
    storageBucket: 'glowup-95ad5.appspot.com',
    measurementId: 'G-BM4EYW9Q71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6i3_X2gtHrNnagWtYI4SKxEmDuUPsDTQ',
    appId: '1:416064020527:android:38ca363dcea28e8aec66da',
    messagingSenderId: '416064020527',
    projectId: 'glowup-95ad5',
    storageBucket: 'glowup-95ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Ye6R-fk1xlmZBYne2wN3yPJKCmqK8Tg',
    appId: '1:416064020527:ios:1972a3f7bb2d8b13ec66da',
    messagingSenderId: '416064020527',
    projectId: 'glowup-95ad5',
    storageBucket: 'glowup-95ad5.appspot.com',
    iosBundleId: 'com.example.beautilly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Ye6R-fk1xlmZBYne2wN3yPJKCmqK8Tg',
    appId: '1:416064020527:ios:1972a3f7bb2d8b13ec66da',
    messagingSenderId: '416064020527',
    projectId: 'glowup-95ad5',
    storageBucket: 'glowup-95ad5.appspot.com',
    iosBundleId: 'com.example.beautilly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHFMA_3F3EO_AAwexwwPaXH73baMqFWpI',
    appId: '1:416064020527:web:0f55a9650ab6fdd5ec66da',
    messagingSenderId: '416064020527',
    projectId: 'glowup-95ad5',
    authDomain: 'glowup-95ad5.firebaseapp.com',
    storageBucket: 'glowup-95ad5.appspot.com',
    measurementId: 'G-42R6N2XTYG',
  );
}
